package tr.edu.hacettepe.da4esdp.service;


import tr.edu.hacettepe.da4esdp.entity.Alternative;
import tr.edu.hacettepe.da4esdp.entity.Fuzzy;

import java.text.DecimalFormat;
import java.util.*;

public class Config {
    // DM1
    static final Fuzzy DM1_ALTERNATIVE_1_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_1_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_1_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_1_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_1_INTERPRETABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_1_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_1_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_1_MAINTAINABILITY = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_1_SPEED = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_2_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_2_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_2_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_2_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_2_INTERPRETABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_2_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_2_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_2_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_2_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_3_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_3_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_3_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_3_OUTLIER = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_3_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_3_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_3_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_3_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_3_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_4_CAUSALITY = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_4_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_4_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_4_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_4_INTERPRETABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_4_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_4_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_4_MAINTAINABILITY = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_4_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_5_CAUSALITY = Fuzzy.LOW;
    static final Fuzzy DM1_ALTERNATIVE_5_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_5_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_5_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_5_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_5_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_5_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_5_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_5_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_6_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_6_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_6_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_6_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_7_UNCERTAINTY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM1_ALTERNATIVE_7_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_7_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM1_ALTERNATIVE_8_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_8_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_8_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_8_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_8_INTERPRETABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_8_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_8_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM1_ALTERNATIVE_8_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM1_ALTERNATIVE_8_SPEED = Fuzzy.AVERAGE;
    //DM2
    static final Fuzzy DM2_ALTERNATIVE_1_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM2_ALTERNATIVE_1_UNCERTAINTY = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_1_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM2_ALTERNATIVE_1_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_1_INTERPRETABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM2_ALTERNATIVE_1_COMPLEXITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM2_ALTERNATIVE_1_ACCURACY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM2_ALTERNATIVE_1_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM2_ALTERNATIVE_1_SPEED = Fuzzy.LOW;
    static final Fuzzy DM2_ALTERNATIVE_2_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_COMPLEXITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_ACCURACY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_MAINTAINABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_2_SPEED = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_3_COMPLEXITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_ACCURACY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_MAINTAINABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_3_SPEED = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_4_CAUSALITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM2_ALTERNATIVE_4_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM2_ALTERNATIVE_4_MISSING = Fuzzy.LOW;
    static final Fuzzy DM2_ALTERNATIVE_4_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM2_ALTERNATIVE_4_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM2_ALTERNATIVE_4_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM2_ALTERNATIVE_4_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_4_MAINTAINABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM2_ALTERNATIVE_4_SPEED = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_5_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_COMPLEXITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_ACCURACY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_MAINTAINABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_5_SPEED = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_COMPLEXITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_ACCURACY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_MAINTAINABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_6_SPEED = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_7_COMPLEXITY = Fuzzy.LOW;
    static final Fuzzy DM2_ALTERNATIVE_7_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_7_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_7_SPEED = Fuzzy.HIGH;
    static final Fuzzy DM2_ALTERNATIVE_8_CAUSALITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_UNCERTAINTY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_MISSING = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_COMPLEXITY = Fuzzy.AVERAGE;
    static final Fuzzy DM2_ALTERNATIVE_8_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM2_ALTERNATIVE_8_MAINTAINABILITY = Fuzzy.OTHER;
    static final Fuzzy DM2_ALTERNATIVE_8_SPEED = Fuzzy.OTHER;
    //DM3
    static final Fuzzy DM3_ALTERNATIVE_1_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_1_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_1_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_1_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_1_INTERPRETABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_1_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_1_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_1_MAINTAINABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_1_SPEED = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_CAUSALITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_UNCERTAINTY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_MISSING = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_COMPLEXITY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_2_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_MAINTAINABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_2_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_3_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_3_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_3_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_3_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_3_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_3_COMPLEXITY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_3_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_3_MAINTAINABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_3_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_4_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_4_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_4_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_4_OUTLIER = Fuzzy.OTHER;
    static final Fuzzy DM3_ALTERNATIVE_4_INTERPRETABILITY = Fuzzy.OTHER;
    static final Fuzzy DM3_ALTERNATIVE_4_COMPLEXITY = Fuzzy.OTHER;
    static final Fuzzy DM3_ALTERNATIVE_4_ACCURACY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_4_MAINTAINABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_4_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_5_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_5_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_5_MISSING = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_5_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_5_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_5_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_5_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_5_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_5_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_6_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_6_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_6_MISSING = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_6_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_6_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_6_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_6_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_6_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_6_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_7_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_7_UNCERTAINTY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_7_MISSING = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_7_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_7_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_7_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_7_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM3_ALTERNATIVE_7_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_7_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM3_ALTERNATIVE_8_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_MISSING = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_8_INTERPRETABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_COMPLEXITY = Fuzzy.LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM3_ALTERNATIVE_8_MAINTAINABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM3_ALTERNATIVE_8_SPEED = Fuzzy.HIGH;
    //DM4
    static final Fuzzy DM4_ALTERNATIVE_1_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_1_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_1_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_1_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_1_INTERPRETABILITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_1_COMPLEXITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_1_ACCURACY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_1_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_1_SPEED = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_2_CAUSALITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_2_UNCERTAINTY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_2_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_2_OUTLIER = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_2_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_2_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_2_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_2_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_2_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_3_CAUSALITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_3_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_3_MISSING = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_3_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_3_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_3_COMPLEXITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_3_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_3_MAINTAINABILITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_3_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_4_CAUSALITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_4_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_4_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_4_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_4_INTERPRETABILITY = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_4_COMPLEXITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_4_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_4_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_4_SPEED = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_5_CAUSALITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_5_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_5_MISSING = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_5_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_5_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_5_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_5_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_5_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_5_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_6_CAUSALITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_6_UNCERTAINTY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_6_MISSING = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_6_OUTLIER = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_6_INTERPRETABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_6_COMPLEXITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_6_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_6_MAINTAINABILITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_6_SPEED = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_7_CAUSALITY = Fuzzy.VERY_LOW;
    static final Fuzzy DM4_ALTERNATIVE_7_UNCERTAINTY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_7_MISSING = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_7_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_7_INTERPRETABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_7_COMPLEXITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_7_ACCURACY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_7_MAINTAINABILITY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_7_SPEED = Fuzzy.VERY_HIGH;
    static final Fuzzy DM4_ALTERNATIVE_8_CAUSALITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_8_UNCERTAINTY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_8_MISSING = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_8_OUTLIER = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_8_INTERPRETABILITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_8_COMPLEXITY = Fuzzy.HIGH;
    static final Fuzzy DM4_ALTERNATIVE_8_ACCURACY = Fuzzy.AVERAGE;
    static final Fuzzy DM4_ALTERNATIVE_8_MAINTAINABILITY = Fuzzy.LOW;
    static final Fuzzy DM4_ALTERNATIVE_8_SPEED = Fuzzy.AVERAGE;
    // Set your alternatives here
    public static String[] alternatives = new String[]{"ANN", "BBN", "DT", "FRBC", "LogR", "NB", "SVM"};
    //    public static String[] alternatives = new String[]{"ANN", "BBN", "DT", "LogR", "NB", "SVM"};
    public static List<Alternative> alternativeList = new ArrayList<>();
    static String[] dms = new String[]{"sandeep", "ezgi", "barbaros", "rana"};
    static Map<Alternative, List<Fuzzy>> dm1Evals = new HashMap<>();
    static Map<Alternative, List<Fuzzy>> dm2Evals = new HashMap<>();
    static Map<Alternative, List<Fuzzy>> dm3Evals = new HashMap<>();
    static Map<Alternative, List<Fuzzy>> dm4Evals = new HashMap<>();
    static DecimalFormat formatter = new DecimalFormat("0.000");

    static {
        alternativeList.add(new Alternative("ANN"));
        alternativeList.add(new Alternative("BBN"));
        alternativeList.add(new Alternative("DT"));
        alternativeList.add(new Alternative("FRBC"));
        alternativeList.add(new Alternative("LinR"));
        alternativeList.add(new Alternative("LogR"));
        alternativeList.add(new Alternative("NB"));
        alternativeList.add(new Alternative("SVM"));
//        alternativeList.forEach(System.out::println);
    }

    static {
        dm1Evals.put(alternativeList.get(0), Arrays.asList(DM1_ALTERNATIVE_1_CAUSALITY, DM1_ALTERNATIVE_1_UNCERTAINTY, DM1_ALTERNATIVE_1_MISSING, DM1_ALTERNATIVE_1_OUTLIER,
                DM1_ALTERNATIVE_1_INTERPRETABILITY, DM1_ALTERNATIVE_1_COMPLEXITY, DM1_ALTERNATIVE_1_ACCURACY, DM1_ALTERNATIVE_1_MAINTAINABILITY, DM1_ALTERNATIVE_1_SPEED));
        dm1Evals.put(alternativeList.get(1), Arrays.asList(DM1_ALTERNATIVE_2_CAUSALITY, DM1_ALTERNATIVE_2_UNCERTAINTY, DM1_ALTERNATIVE_2_MISSING, DM1_ALTERNATIVE_2_OUTLIER,
                DM1_ALTERNATIVE_2_INTERPRETABILITY, DM1_ALTERNATIVE_2_COMPLEXITY, DM1_ALTERNATIVE_2_ACCURACY, DM1_ALTERNATIVE_2_MAINTAINABILITY, DM1_ALTERNATIVE_2_SPEED));
        dm1Evals.put(alternativeList.get(2), Arrays.asList(DM1_ALTERNATIVE_3_CAUSALITY, DM1_ALTERNATIVE_3_UNCERTAINTY, DM1_ALTERNATIVE_3_MISSING, DM1_ALTERNATIVE_3_OUTLIER,
                DM1_ALTERNATIVE_3_INTERPRETABILITY, DM1_ALTERNATIVE_3_COMPLEXITY, DM1_ALTERNATIVE_3_ACCURACY, DM1_ALTERNATIVE_3_MAINTAINABILITY, DM1_ALTERNATIVE_3_SPEED));
        dm1Evals.put(alternativeList.get(3), Arrays.asList(DM1_ALTERNATIVE_4_CAUSALITY, DM1_ALTERNATIVE_4_UNCERTAINTY, DM1_ALTERNATIVE_4_MISSING, DM1_ALTERNATIVE_4_OUTLIER,
                DM1_ALTERNATIVE_4_INTERPRETABILITY, DM1_ALTERNATIVE_4_COMPLEXITY, DM1_ALTERNATIVE_4_ACCURACY, DM1_ALTERNATIVE_4_MAINTAINABILITY, DM1_ALTERNATIVE_4_SPEED));
        dm1Evals.put(alternativeList.get(4), Arrays.asList(DM1_ALTERNATIVE_5_CAUSALITY, DM1_ALTERNATIVE_5_UNCERTAINTY, DM1_ALTERNATIVE_5_MISSING, DM1_ALTERNATIVE_5_OUTLIER,
                DM1_ALTERNATIVE_5_INTERPRETABILITY, DM1_ALTERNATIVE_5_COMPLEXITY, DM1_ALTERNATIVE_5_ACCURACY, DM1_ALTERNATIVE_5_MAINTAINABILITY, DM1_ALTERNATIVE_5_SPEED));
        dm1Evals.put(alternativeList.get(5), Arrays.asList(DM1_ALTERNATIVE_6_CAUSALITY, DM1_ALTERNATIVE_6_UNCERTAINTY, DM1_ALTERNATIVE_6_MISSING, DM1_ALTERNATIVE_6_OUTLIER,
                DM1_ALTERNATIVE_6_INTERPRETABILITY, DM1_ALTERNATIVE_6_COMPLEXITY, DM1_ALTERNATIVE_6_ACCURACY, DM1_ALTERNATIVE_6_MAINTAINABILITY, DM1_ALTERNATIVE_6_SPEED));
        dm1Evals.put(alternativeList.get(6), Arrays.asList(DM1_ALTERNATIVE_7_CAUSALITY, DM1_ALTERNATIVE_7_UNCERTAINTY, DM1_ALTERNATIVE_7_MISSING, DM1_ALTERNATIVE_7_OUTLIER,
                DM1_ALTERNATIVE_7_INTERPRETABILITY, DM1_ALTERNATIVE_7_COMPLEXITY, DM1_ALTERNATIVE_7_ACCURACY, DM1_ALTERNATIVE_7_MAINTAINABILITY, DM1_ALTERNATIVE_7_SPEED));
        dm1Evals.put(alternativeList.get(7), Arrays.asList(DM1_ALTERNATIVE_8_CAUSALITY, DM1_ALTERNATIVE_8_UNCERTAINTY, DM1_ALTERNATIVE_8_MISSING, DM1_ALTERNATIVE_8_OUTLIER,
                DM1_ALTERNATIVE_8_INTERPRETABILITY, DM1_ALTERNATIVE_8_COMPLEXITY, DM1_ALTERNATIVE_8_ACCURACY, DM1_ALTERNATIVE_8_MAINTAINABILITY, DM1_ALTERNATIVE_8_SPEED));
    }

    static {
        dm2Evals.put(alternativeList.get(0), Arrays.asList(DM2_ALTERNATIVE_1_CAUSALITY, DM2_ALTERNATIVE_1_UNCERTAINTY, DM2_ALTERNATIVE_1_MISSING, DM2_ALTERNATIVE_1_OUTLIER,
                DM2_ALTERNATIVE_1_INTERPRETABILITY, DM2_ALTERNATIVE_1_COMPLEXITY, DM2_ALTERNATIVE_1_ACCURACY, DM2_ALTERNATIVE_1_MAINTAINABILITY, DM2_ALTERNATIVE_1_SPEED));
        dm2Evals.put(alternativeList.get(1), Arrays.asList(DM2_ALTERNATIVE_2_CAUSALITY, DM2_ALTERNATIVE_2_UNCERTAINTY, DM2_ALTERNATIVE_2_MISSING, DM2_ALTERNATIVE_2_OUTLIER,
                DM2_ALTERNATIVE_2_INTERPRETABILITY, DM2_ALTERNATIVE_2_COMPLEXITY, DM2_ALTERNATIVE_2_ACCURACY, DM2_ALTERNATIVE_2_MAINTAINABILITY, DM2_ALTERNATIVE_2_SPEED));
        dm2Evals.put(alternativeList.get(2), Arrays.asList(DM2_ALTERNATIVE_3_CAUSALITY, DM2_ALTERNATIVE_3_UNCERTAINTY, DM2_ALTERNATIVE_3_MISSING, DM2_ALTERNATIVE_3_OUTLIER,
                DM2_ALTERNATIVE_3_INTERPRETABILITY, DM2_ALTERNATIVE_3_COMPLEXITY, DM2_ALTERNATIVE_3_ACCURACY, DM2_ALTERNATIVE_3_MAINTAINABILITY, DM2_ALTERNATIVE_3_SPEED));
        dm2Evals.put(alternativeList.get(3), Arrays.asList(DM2_ALTERNATIVE_4_CAUSALITY, DM2_ALTERNATIVE_4_UNCERTAINTY, DM2_ALTERNATIVE_4_MISSING, DM2_ALTERNATIVE_4_OUTLIER,
                DM2_ALTERNATIVE_4_INTERPRETABILITY, DM2_ALTERNATIVE_4_COMPLEXITY, DM2_ALTERNATIVE_4_ACCURACY, DM2_ALTERNATIVE_4_MAINTAINABILITY, DM2_ALTERNATIVE_4_SPEED));
        dm2Evals.put(alternativeList.get(4), Arrays.asList(DM2_ALTERNATIVE_5_CAUSALITY, DM2_ALTERNATIVE_5_UNCERTAINTY, DM2_ALTERNATIVE_5_MISSING, DM2_ALTERNATIVE_5_OUTLIER,
                DM2_ALTERNATIVE_5_INTERPRETABILITY, DM2_ALTERNATIVE_5_COMPLEXITY, DM2_ALTERNATIVE_5_ACCURACY, DM2_ALTERNATIVE_5_MAINTAINABILITY, DM2_ALTERNATIVE_5_SPEED));
        dm2Evals.put(alternativeList.get(5), Arrays.asList(DM2_ALTERNATIVE_6_CAUSALITY, DM2_ALTERNATIVE_6_UNCERTAINTY, DM2_ALTERNATIVE_6_MISSING, DM2_ALTERNATIVE_6_OUTLIER,
                DM2_ALTERNATIVE_6_INTERPRETABILITY, DM2_ALTERNATIVE_6_COMPLEXITY, DM2_ALTERNATIVE_6_ACCURACY, DM2_ALTERNATIVE_6_MAINTAINABILITY, DM2_ALTERNATIVE_6_SPEED));
        dm2Evals.put(alternativeList.get(6), Arrays.asList(DM2_ALTERNATIVE_7_CAUSALITY, DM2_ALTERNATIVE_7_UNCERTAINTY, DM2_ALTERNATIVE_7_MISSING, DM2_ALTERNATIVE_7_OUTLIER,
                DM2_ALTERNATIVE_7_INTERPRETABILITY, DM2_ALTERNATIVE_7_COMPLEXITY, DM2_ALTERNATIVE_7_ACCURACY, DM2_ALTERNATIVE_7_MAINTAINABILITY, DM2_ALTERNATIVE_7_SPEED));
        dm2Evals.put(alternativeList.get(7), Arrays.asList(DM2_ALTERNATIVE_8_CAUSALITY, DM2_ALTERNATIVE_8_UNCERTAINTY, DM2_ALTERNATIVE_8_MISSING, DM2_ALTERNATIVE_8_OUTLIER,
                DM2_ALTERNATIVE_8_INTERPRETABILITY, DM2_ALTERNATIVE_8_COMPLEXITY, DM2_ALTERNATIVE_8_ACCURACY, DM2_ALTERNATIVE_8_MAINTAINABILITY, DM2_ALTERNATIVE_8_SPEED));
    }

    static {
        dm3Evals.put(alternativeList.get(0), Arrays.asList(DM3_ALTERNATIVE_1_CAUSALITY, DM3_ALTERNATIVE_1_UNCERTAINTY, DM3_ALTERNATIVE_1_MISSING, DM3_ALTERNATIVE_1_OUTLIER,
                DM3_ALTERNATIVE_1_INTERPRETABILITY, DM3_ALTERNATIVE_1_COMPLEXITY, DM3_ALTERNATIVE_1_ACCURACY, DM3_ALTERNATIVE_1_MAINTAINABILITY, DM3_ALTERNATIVE_1_SPEED));
        dm3Evals.put(alternativeList.get(1), Arrays.asList(DM3_ALTERNATIVE_2_CAUSALITY, DM3_ALTERNATIVE_2_UNCERTAINTY, DM3_ALTERNATIVE_2_MISSING, DM3_ALTERNATIVE_2_OUTLIER,
                DM3_ALTERNATIVE_2_INTERPRETABILITY, DM3_ALTERNATIVE_2_COMPLEXITY, DM3_ALTERNATIVE_2_ACCURACY, DM3_ALTERNATIVE_2_MAINTAINABILITY, DM3_ALTERNATIVE_2_SPEED));
        dm3Evals.put(alternativeList.get(2), Arrays.asList(DM3_ALTERNATIVE_3_CAUSALITY, DM3_ALTERNATIVE_3_UNCERTAINTY, DM3_ALTERNATIVE_3_MISSING, DM3_ALTERNATIVE_3_OUTLIER,
                DM3_ALTERNATIVE_3_INTERPRETABILITY, DM3_ALTERNATIVE_3_COMPLEXITY, DM3_ALTERNATIVE_3_ACCURACY, DM3_ALTERNATIVE_3_MAINTAINABILITY, DM3_ALTERNATIVE_3_SPEED));
        dm3Evals.put(alternativeList.get(3), Arrays.asList(DM3_ALTERNATIVE_4_CAUSALITY, DM3_ALTERNATIVE_4_UNCERTAINTY, DM3_ALTERNATIVE_4_MISSING, DM3_ALTERNATIVE_4_OUTLIER,
                DM3_ALTERNATIVE_4_INTERPRETABILITY, DM3_ALTERNATIVE_4_COMPLEXITY, DM3_ALTERNATIVE_4_ACCURACY, DM3_ALTERNATIVE_4_MAINTAINABILITY, DM3_ALTERNATIVE_4_SPEED));
        dm3Evals.put(alternativeList.get(4), Arrays.asList(DM3_ALTERNATIVE_5_CAUSALITY, DM3_ALTERNATIVE_5_UNCERTAINTY, DM3_ALTERNATIVE_5_MISSING, DM3_ALTERNATIVE_5_OUTLIER,
                DM3_ALTERNATIVE_5_INTERPRETABILITY, DM3_ALTERNATIVE_5_COMPLEXITY, DM3_ALTERNATIVE_5_ACCURACY, DM3_ALTERNATIVE_5_MAINTAINABILITY, DM3_ALTERNATIVE_5_SPEED));
        dm3Evals.put(alternativeList.get(5), Arrays.asList(DM3_ALTERNATIVE_6_CAUSALITY, DM3_ALTERNATIVE_6_UNCERTAINTY, DM3_ALTERNATIVE_6_MISSING, DM3_ALTERNATIVE_6_OUTLIER,
                DM3_ALTERNATIVE_6_INTERPRETABILITY, DM3_ALTERNATIVE_6_COMPLEXITY, DM3_ALTERNATIVE_6_ACCURACY, DM3_ALTERNATIVE_6_MAINTAINABILITY, DM3_ALTERNATIVE_6_SPEED));
        dm3Evals.put(alternativeList.get(6), Arrays.asList(DM3_ALTERNATIVE_7_CAUSALITY, DM3_ALTERNATIVE_7_UNCERTAINTY, DM3_ALTERNATIVE_7_MISSING, DM3_ALTERNATIVE_7_OUTLIER,
                DM3_ALTERNATIVE_7_INTERPRETABILITY, DM3_ALTERNATIVE_7_COMPLEXITY, DM3_ALTERNATIVE_7_ACCURACY, DM3_ALTERNATIVE_7_MAINTAINABILITY, DM3_ALTERNATIVE_7_SPEED));
        dm3Evals.put(alternativeList.get(7), Arrays.asList(DM3_ALTERNATIVE_8_CAUSALITY, DM3_ALTERNATIVE_8_UNCERTAINTY, DM3_ALTERNATIVE_8_MISSING, DM3_ALTERNATIVE_8_OUTLIER,
                DM3_ALTERNATIVE_8_INTERPRETABILITY, DM3_ALTERNATIVE_8_COMPLEXITY, DM3_ALTERNATIVE_8_ACCURACY, DM3_ALTERNATIVE_8_MAINTAINABILITY, DM3_ALTERNATIVE_8_SPEED));
    }

    static {
        dm4Evals.put(alternativeList.get(0), Arrays.asList(DM4_ALTERNATIVE_1_CAUSALITY, DM4_ALTERNATIVE_1_UNCERTAINTY, DM4_ALTERNATIVE_1_MISSING, DM4_ALTERNATIVE_1_OUTLIER,
                DM4_ALTERNATIVE_1_INTERPRETABILITY, DM4_ALTERNATIVE_1_COMPLEXITY, DM4_ALTERNATIVE_1_ACCURACY, DM4_ALTERNATIVE_1_MAINTAINABILITY, DM4_ALTERNATIVE_1_SPEED));
        dm4Evals.put(alternativeList.get(1), Arrays.asList(DM4_ALTERNATIVE_2_CAUSALITY, DM4_ALTERNATIVE_2_UNCERTAINTY, DM4_ALTERNATIVE_2_MISSING, DM4_ALTERNATIVE_2_OUTLIER,
                DM4_ALTERNATIVE_2_INTERPRETABILITY, DM4_ALTERNATIVE_2_COMPLEXITY, DM4_ALTERNATIVE_2_ACCURACY, DM4_ALTERNATIVE_2_MAINTAINABILITY, DM4_ALTERNATIVE_2_SPEED));
        dm4Evals.put(alternativeList.get(2), Arrays.asList(DM4_ALTERNATIVE_3_CAUSALITY, DM4_ALTERNATIVE_3_UNCERTAINTY, DM4_ALTERNATIVE_3_MISSING, DM4_ALTERNATIVE_3_OUTLIER,
                DM4_ALTERNATIVE_3_INTERPRETABILITY, DM4_ALTERNATIVE_3_COMPLEXITY, DM4_ALTERNATIVE_3_ACCURACY, DM4_ALTERNATIVE_3_MAINTAINABILITY, DM4_ALTERNATIVE_3_SPEED));
        dm4Evals.put(alternativeList.get(3), Arrays.asList(DM4_ALTERNATIVE_4_CAUSALITY, DM4_ALTERNATIVE_4_UNCERTAINTY, DM4_ALTERNATIVE_4_MISSING, DM4_ALTERNATIVE_4_OUTLIER,
                DM4_ALTERNATIVE_4_INTERPRETABILITY, DM4_ALTERNATIVE_4_COMPLEXITY, DM4_ALTERNATIVE_4_ACCURACY, DM4_ALTERNATIVE_4_MAINTAINABILITY, DM4_ALTERNATIVE_4_SPEED));
        dm4Evals.put(alternativeList.get(4), Arrays.asList(DM4_ALTERNATIVE_5_CAUSALITY, DM4_ALTERNATIVE_5_UNCERTAINTY, DM4_ALTERNATIVE_5_MISSING, DM4_ALTERNATIVE_5_OUTLIER,
                DM4_ALTERNATIVE_5_INTERPRETABILITY, DM4_ALTERNATIVE_5_COMPLEXITY, DM4_ALTERNATIVE_5_ACCURACY, DM4_ALTERNATIVE_5_MAINTAINABILITY, DM4_ALTERNATIVE_5_SPEED));
        dm4Evals.put(alternativeList.get(5), Arrays.asList(DM4_ALTERNATIVE_6_CAUSALITY, DM4_ALTERNATIVE_6_UNCERTAINTY, DM4_ALTERNATIVE_6_MISSING, DM4_ALTERNATIVE_6_OUTLIER,
                DM4_ALTERNATIVE_6_INTERPRETABILITY, DM4_ALTERNATIVE_6_COMPLEXITY, DM4_ALTERNATIVE_6_ACCURACY, DM4_ALTERNATIVE_6_MAINTAINABILITY, DM4_ALTERNATIVE_6_SPEED));
        dm4Evals.put(alternativeList.get(6), Arrays.asList(DM4_ALTERNATIVE_7_CAUSALITY, DM4_ALTERNATIVE_7_UNCERTAINTY, DM4_ALTERNATIVE_7_MISSING, DM4_ALTERNATIVE_7_OUTLIER,
                DM4_ALTERNATIVE_7_INTERPRETABILITY, DM4_ALTERNATIVE_7_COMPLEXITY, DM4_ALTERNATIVE_7_ACCURACY, DM4_ALTERNATIVE_7_MAINTAINABILITY, DM4_ALTERNATIVE_7_SPEED));
        dm4Evals.put(alternativeList.get(7), Arrays.asList(DM4_ALTERNATIVE_8_CAUSALITY, DM4_ALTERNATIVE_8_UNCERTAINTY, DM4_ALTERNATIVE_8_MISSING, DM4_ALTERNATIVE_8_OUTLIER,
                DM4_ALTERNATIVE_8_INTERPRETABILITY, DM4_ALTERNATIVE_8_COMPLEXITY, DM4_ALTERNATIVE_8_ACCURACY, DM4_ALTERNATIVE_8_MAINTAINABILITY, DM4_ALTERNATIVE_8_SPEED));
    }

}
